# Generated by Django 3.1.1 on 2020-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('e_id', models.IntegerField(max_length=6)),
                ('e_type', models.CharField(choices=[('em', 'employee'), ('mn', 'manager')], default='em', max_length=2)),
            ],
        ),
    ]
