# Generated by Django 3.1.1 on 2020-09-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0002_user_no_of_leaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_id',
            field=models.IntegerField(),
        ),
    ]
