# Generated by Django 3.0.3 on 2020-09-06 06:46

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0002_auto_20200906_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='e_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='no_of_leaves',
        ),
        migrations.AlterField(
            model_name='leave',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 12, 16, 59, 308020)),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_type', models.CharField(choices=[('em', 'employee'), ('mn', 'manager')], default='em', max_length=2)),
                ('no_of_leaves', models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='leaveApp.User')),
            ],
        ),
    ]
