# Generated by Django 3.1.1 on 2020-09-05 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0004_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='e_id',
            field=models.CharField(max_length=10),
        ),
    ]
