# Generated by Django 3.1.1 on 2020-09-05 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0005_auto_20200905_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='user',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='leaveApp.user'),
        ),
    ]
