# Generated by Django 3.0.3 on 2020-09-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0007_auto_20200906_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='req_date',
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_type',
            field=models.CharField(choices=[('employee', 'employee'), ('manager', 'manager'), ('admin', 'admin')], default='employee', max_length=10),
        ),
    ]
