# Generated by Django 3.1.1 on 2020-09-05 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0007_auto_20200905_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='req_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='e_id',
            field=models.CharField(max_length=25),
        ),
    ]
