# Generated by Django 3.1.1 on 2020-09-05 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0008_auto_20200905_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 15, 53, 38, 303258)),
        ),
    ]
