# Generated by Django 3.0.3 on 2020-09-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0009_auto_20200906_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='e_type',
            field=models.CharField(choices=[('employee', 'employee'), ('manager', 'manager')], default='employee', max_length=10),
        ),
    ]
