# Generated by Django 3.0.3 on 2020-09-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0010_auto_20200906_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='e_type',
        ),
    ]
