# Generated by Django 3.0.3 on 2020-09-06 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0016_auto_20200906_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 6, 20, 50, 50, 691539)),
        ),
    ]
