# Generated by Django 3.1.1 on 2020-09-09 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0022_auto_20200909_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 10, 55, 43, 378577)),
        ),
    ]
