# Generated by Django 3.1.1 on 2020-09-09 06:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0024_auto_20200909_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='leave',
            name='req_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 9, 11, 40, 54, 335580)),
        ),
    ]
