# Generated by Django 3.1.1 on 2020-09-09 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveApp', '0025_auto_20200909_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='req_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
